# Generated by Django 3.1 on 2021-03-11 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.IntegerField()),
                ('issue_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=100)),
                ('printer_serial', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('printer_model', models.CharField(max_length=100)),
                ('printer_make', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=225)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='app11.printerissues')),
            ],
        ),
        migrations.AddField(
            model_name='printerissues',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printerissues', to='app11.printers'),
        ),
    ]
